### PR TITLE
Get plots

### PR DESCRIPTION
**Pull request by aleckzts**
Added data from harvester API get_plots
```
# HELP chia_plots Number of plots currently using.
# TYPE chia_plots gauge
chia_plots 5

# HELP chia_plots_failed_to_open Number of plots files failed to open.
# TYPE chia_plots_failed_to_open gauge
chia_plots_failed_to_open 0

# HELP chia_plots_not_found Number of plots files not found.
# TYPE chia_plots_not_found gauge
chia_plots_not_found 0
```

### CODE REVIEW

**Comment by retzkek** [comment]
Thanks for contributing, these metrics look good. Three things:

1. This PR appears to include the changes from #4, which in turn includes the changes from #6; it would be nice to merge them individually, which may get a bit ugly. Think you can update the branches to only include the relevant changes? Otherwise I'll just merge this to capture everything.
2. Please `go fmt` your code. I highly recommend having your editor run it whenever you save.
3. Please update the README

Again thanks for the PRs, I really appreciate it!

**Comment by aleckzts** [comment]
I will try to change the PRs with only 1 change each.. thanks

**Comment by snoby** [comment]
Looking forward to these changes

**Comment by aleckzts** [comment]
I think that all changes are made

**Pull request merged**
